[Path]
Base=%PATH%

[Git]
Path=%PAL:CommonFilesDir%\Git
; Change "HOME" to misc folder
ChangeUnixHome=true

[MinGW]
Path=%PAL:CommonFilesDir%\MinGW

[Java]
Path=%PAL:CommonFilesDir%\Java
; Change "GRADLE_USER_HOME" to misc folder
ChangeGradleUserHome=true

[Python]
Path=%PAL:CommonFilesDir%\Python
; Change "PYTHONUSERBASE" to misc folder
ChangePythonUserBase=true
; Change "PIP_CACHE_DIR" to misc folder
ChangePipCache=true
; Delete pip cache if the above is true
DeletePipCacheOnExit=true
; Change "JUPYTER_DATA_DIR" to misc folder
ChangeJupyterData=true

[R]
Path=%PAL:CommonFilesDir%\R
; Change "R_LIBS_USER" to misc folder
ChangeRLibsUser=true

[NodeJS]
Path=%PAL:CommonFilesDir%\NodeJS
; Change "NPM_CONFIG_PREFIX" to misc folder
ChangeNpmPrefix=true
; Delete npm cache if the above is true
DeleteNpmCacheOnExit=true

[Bun]
Path=%PAL:CommonFilesDir%\Bun
; Change "BUN_INSTALL" to misc folder
ChangeBunInstall=true
; Delete Bun cache if the above is true
DeleteBunCacheOnExit=true

[Go]
Path=%PAL:CommonFilesDir%\Go
; Change "GOPATH" to misc folder
ChangeGoPath=true

[Rust]
Path=%PAL:CommonFilesDir%\Rust
; Change "CARGO_HOME" to misc folder
ChangeCargoHome=true
; Delete Cargo cache if the above is true
DeleteCargeCacheOnExit=true

[Android]
StudioPath=%PAL:CommonFilesDir%\Android\Studio
; Change "idea.config.path" to misc folder
ChangeAndroidStudioConfig=true
; Force change SDK and AVD path with junction
; SDK and AVD path must exist for this to work
UseSdkAvdJunction=true
SdkPath=%PAL:CommonFilesDir%\Android\Sdk
AvdPath=%PAL:CommonFilesDir%\Android\Avd

[Flutter]
Path=%PAL:CommonFilesDir%\Flutter
; Change "PUB_CACHE" to misc folder
ChangePubCache=true

[PlatformIO]
; Change "PLATFORMIO_CORE_DIR" to misc folder
ChangePlatformIOCore=true