[Launch]
; Additional parameters to pass to VS Code
AdditionalParameters=
; Override "PATH" variable for the VS Code process
; Use "%PATH%;XXX" to append directory to original "PATH"
; Use "%__clean__%" to emulate clean Windows 11 "PATH"
OverridePath=

[Git]
; Will check "$GitDir\cmd\git.exe"
GitDir=%PAL:CommonFilesDir%\Git
; Change to "Data\misc"
ChangeUnixHome=true

[MinGW]
; Will check "$MinGWDir\bin\gcc.exe"
MinGWDir=%PAL:CommonFilesDir%\MinGW

[Java]
; Will check "$JavaDir\bin\java.exe"
JavaDir=%PAL:CommonFilesDir%\OpenJDK
; Change to "Data\misc\.gradle"
ChangeGradleUserHome=true

[Python]
; Will check "$PythonDir\python.exe"
PythonDir=%PAL:CommonFilesDir%\Python
; Change to "Data\misc\AppData\Roaming\Python"
ChangePythonUserBase=true
; Change to "Data\misc\AppData\Local\pip\cache"
ChangePipCache=true
; Change to "Data\misc\AppData\Roaming\jupyter"
ChangeJupyterData=true

[R]
; Will check "$RDir\bin\R.exe"
RDir=%PAL:CommonFilesDir%\R
; Change to "Data\misc\AppData\Local\R\win-library\X.Y"
ChangeRLibsUser=true

[NodeJS]
; Will check "$NodeJSDir\node.exe"
NodeJSDir=%PAL:CommonFilesDir%\Node.js
; Change to "Data\misc\AppData\Roaming\npm"
ChangeNPMPrefix=true

[Bun]
; Will check "$BunDir\bin\bun.exe"
BunDir=%PAL:CommonFilesDir%\Bun
; Change to "Data\misc\.bun"
ChangeBunInstall=true

[Go]
; Will check "$GoDir\bin\go.exe"
GoDir=%PAL:CommonFilesDir%\Go
; Change to "Data\misc\Go"
ChangeGoPath=true

[Rust]
; Will check "$RustDir\bin\rustc.exe"
RustDir=%PAL:CommonFilesDir%\Rust
; Change to "Data\misc\Rust\.cargo"
ChangeCargoHome=true

[Android]
; Will check "$AndroidStudioDir\bin\studio64.exe"
AndroidStudioDir=%PAL:CommonFilesDir%\Android\Studio
; Change to "Data\misc\.AndroidStudio"
ChangeAndroidStudioConfig=true
; Create junctions to directories below (the path must exist)
; Android user home will also be changed to "Data\misc\.android"
CreateJunctionsToAndroid=true
; "$PathToAndroidSdk" will link to "%LocalAppData%\Android\Sdk"
PathToAndroidSdk=%PAL:CommonFilesDir%\Android\Sdk
; "$PathToAndroidAvd" will link to "%UserProfile%\.android\avd"
PathToAndroidAvd=%PAL:CommonFilesDir%\Android\Avd

[Flutter]
; Will check "$FlutterDir\bin\dart.bat"
FlutterDir=%PAL:CommonFilesDir%\Flutter
; Change to "Data\misc\AppData\Local\Pub\Cache"
ChangePubCache=true

[PlatformIO]
; Change to "Data\misc\.platformio"
ChangePlatformIOCore=true